replica_count: 1

strategy:
  max_surge: 1
  max_unavailable: 1

annotations:
  enabled: true
  dot_skillsoft: |
     ${context.dotSkillsoft.podAnnotations}
envState: ${workflow.variables.EnvState}

container:
  image_pull_policy: IfNotPresent
  image:
    repository: 510467250861.dkr.ecr.us-east-1.amazonaws.com
    tag: ${workflow.variables.Dockertag}

resources:
  cpu:
    limit: 500m
    request: 500m
  memory:
    limit: 512Mi
    request: 512Mi

metadata:
  labels:
    app: coaching
  namespace: coaching

configmap:
  enabled: true
  PORT: '8080'
  HOST: '0.0.0.0'
  env: 'production'

readinessProbe:
  httpGet:
    path: '/public/health/v1/ping'
    port: 8080
livenessProbe:
  port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 1

ingress_external:
  enabled: false
  host: must_override

ingress_restricted:
  enabled: false
  host: must_override

peerauthentication:
  enabled: true

verticalpodautoscaler:
  enabled: true

virtualservice_internal:
  enabled: false

virtualservice_restricted:
  enabled: false
  host: must_override

newrelic:
  enabled: true 
  license_key: ${secrets.getValue("new-relic-license-key-${env.name}")}
  no_config_file: true
  labels: must_override 
  
c_data_env_DEV_LD_CLIENTSIDE_ID: '6193cac8e6fcb91547c5829b'
c_data_env_PROD_LD_CLIENTSIDE_ID: '6193cac8e6fcb91547c5829c'